package classifier

import (
	"testing"
)

func TestClassifierWithComplexScenarios(t *testing.T) {
	testsRunner(t, []TestCase{
		{
			name:     "Multi-block template inheritance pattern",
			template: "{{<layout}}\n{{$title}}Page Title{{/title}}\n{{$content}}\n  <p>Page content</p>\n  <ul>\n    <li>Item 1</li>\n    <li>Item 2</li>\n  </ul>\n{{/content}}\n{{/layout}}",
			want: Lines{
				0: {Type: StandaloneLine, Segments: parentBeginSegments},
				1: {Type: InlineLine, Segments: Segments{blockBeginSegment, textContentSegment, blockEndSegment}},
				2: {Type: StandaloneLine, Segments: blockBeginSegments},
				3: {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				4: {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				5: {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				6: {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				7: {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				8: {Type: StandaloneLine, Segments: blockEndSegments},
				9: {Type: StandaloneLine, Segments: parentEndSegments},
			},
			comment: "Complex template inheritance with nested content blocks",
		},
		{
			name:     "Multi-block template inheritance pattern with trailing newline",
			template: "{{<layout}}\n{{$title}}Page Title{{/title}}\n{{$content}}\n  <p>Page content</p>\n  <ul>\n    <li>Item 1</li>\n    <li>Item 2</li>\n  </ul>\n{{/content}}\n{{/layout}}\n",
			want: Lines{
				0:  {Type: StandaloneLine, Segments: parentBeginSegments},
				1:  {Type: InlineLine, Segments: Segments{blockBeginSegment, textContentSegment, blockEndSegment}},
				2:  {Type: StandaloneLine, Segments: blockBeginSegments},
				3:  {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				4:  {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				5:  {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				6:  {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				7:  {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				8:  {Type: StandaloneLine, Segments: blockEndSegments},
				9:  {Type: StandaloneLine, Segments: parentEndSegments},
				10: {Type: EmptyLine},
			},
			comment: "Complex template inheritance with nested content blocks; trailing newline creates an empty line",
		},
		{
			name:     "Nested sections with indentation",
			template: "{{#outer}}\n  {{#inner}}\n    {{value}}\n  {{/inner}}\n{{/outer}}",
			want: Lines{
				0: {Type: StandaloneLine, Segments: sectionBeginSegments},
				1: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, sectionBeginSegment}},
				2: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, varTagSegment}},
				3: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, sectionEndSegment}},
				4: {Type: StandaloneLine, Segments: sectionEndSegments},
			},
			comment: "Nested sections with consistent indentation should all be standalone",
		},
		{
			name:     "Nested sections with indentation and trailing newline",
			template: "{{#outer}}\n  {{#inner}}\n    {{value}}\n  {{/inner}}\n{{/outer}}\n",
			want: Lines{
				0: {Type: StandaloneLine, Segments: sectionBeginSegments},
				1: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, sectionBeginSegment}},
				2: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, varTagSegment}},
				3: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, sectionEndSegment}},
				4: {Type: StandaloneLine, Segments: sectionEndSegments},
				5: {Type: EmptyLine},
			},
			comment: "Nested sections with consistent indentation should all be standalone; trailing newline creates an empty line",
		},
		{
			name:     "Tag with dot notation and special characters",
			template: "{{user.name}}\n{{#user.settings.notifications}}\n  {{user.email}}\n{{/user.settings.notifications}}",
			want: Lines{
				0: {Type: StandaloneLine, Segments: varTagSegments},
				1: {Type: StandaloneLine, Segments: sectionBeginSegments},
				2: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, varTagSegment}},
				3: {Type: StandaloneLine, Segments: sectionEndSegments},
			},
			comment: "Tags with complex paths and dot notation can be standalone",
		},
		{
			name:     "Tag with dot notation and special characters with trailing newline",
			template: "{{user.name}}\n{{#user.settings.notifications}}\n  {{user.email}}\n{{/user.settings.notifications}}\n",
			want: Lines{
				0: {Type: StandaloneLine, Segments: varTagSegments},
				1: {Type: StandaloneLine, Segments: sectionBeginSegments},
				2: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, varTagSegment}},
				3: {Type: StandaloneLine, Segments: sectionEndSegments},
				4: {Type: EmptyLine},
			},
			comment: "Tags with complex paths and dot notation can be standalone; trailing newline creates an empty line",
		},
		{
			name:     "Comment tags",
			template: "{{! This is a comment }}\nContent\n{{! \n  Multi-line\n  comment\n}}\nMore content",
			want: Lines{
				0: {Type: StandaloneLine, Segments: commentTagSegments},
				1: {Type: TextLine, Segments: textContentSegments},
				2: {Type: InlineLine, Segments: multilineCommentBegins},
				3: {Type: InlineLine, Segments: multilineCommentMiddles},
				4: {Type: InlineLine, Segments: multilineCommentMiddles},
				5: {Type: InlineLine, Segments: multilineCommentEnds},
				6: {Type: TextLine, Segments: textContentSegments},
			},
			comment: "Comment tags, including multi-line comments, with proper multi-line tag designation",
		},
		{
			name:     "Comment tags with trailing newline",
			template: "{{! This is a comment }}\nContent\n{{! \n  Multi-line\n  comment\n}}\nMore content\n",
			want: Lines{
				0: {Type: StandaloneLine, Segments: commentTagSegments},
				1: {Type: TextLine, Segments: textContentSegments},
				2: {Type: InlineLine, Segments: multilineCommentBegins},
				3: {Type: InlineLine, Segments: multilineCommentMiddles},
				4: {Type: InlineLine, Segments: multilineCommentMiddles},
				5: {Type: InlineLine, Segments: multilineCommentEnds},
				6: {Type: TextLine, Segments: textContentSegments},
				7: {Type: EmptyLine},
			},
			comment: "Comment tags, including multi-line comments, with proper multi-line tag designation; trailing newline creates an empty line",
		},
		{
			name:     "Comment tags with leading and trailing whitespace",
			template: "   {{! This is a comment }}   \nContent\n   {{! \n  Multi-line\n  comment\n}}   \nMore content",
			want: Lines{
				0: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, commentTagSegment, whitespaceSegment}},
				1: {Type: TextLine, Segments: textContentSegments},
				2: {Type: InlineLine, Segments: Segments{whitespaceSegment, multilineCommentBegin}},
				3: {Type: InlineLine, Segments: Segments{multilineCommentMiddle}},
				4: {Type: InlineLine, Segments: Segments{multilineCommentMiddle}},
				5: {Type: InlineLine, Segments: Segments{multilineCommentEnd, whitespaceSegment}},
				6: {Type: TextLine, Segments: textContentSegments},
			},
			comment: "Comment tags, including multi-line comments, with proper multi-line tag designation",
		},
		{
			name:     "Comment tags with leading and trailing whitespace and with trailing newline",
			template: "   {{! This is a comment }}   \nContent\n   {{! \n  Multi-line\n  comment\n}}   \nMore content\n",
			want: Lines{
				0: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, commentTagSegment, whitespaceSegment}},
				1: {Type: TextLine, Segments: textContentSegments},
				2: {Type: InlineLine, Segments: Segments{whitespaceSegment, multilineCommentBegin}},
				3: {Type: InlineLine, Segments: Segments{multilineCommentMiddle}},
				4: {Type: InlineLine, Segments: Segments{multilineCommentMiddle}},
				5: {Type: InlineLine, Segments: Segments{multilineCommentEnd, whitespaceSegment}},
				6: {Type: TextLine, Segments: textContentSegments},
				7: {Type: EmptyLine},
			},
			comment: "Comment tags, including multi-line comments, with proper multi-line tag designation; trailing newline creates an empty line",
		},
		{
			name:     "Complex multi-line template",
			template: "Before\n{{#section}}\n  {{name}}\n{{/section}}\nAfter",
			want: Lines{
				0: {Type: TextLine, Segments: textContentSegments},
				1: {Type: StandaloneLine, Segments: sectionBeginSegments},
				2: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, varTagSegment}},
				3: {Type: StandaloneLine, Segments: sectionEndSegments},
				4: {Type: TextLine, Segments: textContentSegments},
			},
			comment: "Section opening and closing tags should be standalone",
		},
		{
			name:     "Complex multi-line template with trailing newline",
			template: "Before\n{{#section}}\n  {{name}}\n{{/section}}\nAfter\n",
			want: Lines{
				0: {Type: TextLine, Segments: textContentSegments},
				1: {Type: StandaloneLine, Segments: sectionBeginSegments},
				2: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, varTagSegment}},
				3: {Type: StandaloneLine, Segments: sectionEndSegments},
				4: {Type: TextLine, Segments: textContentSegments},
				5: {Type: EmptyLine},
			},
			comment: "Section opening and closing tags should be standalone; trailing newline creates an empty line",
		},
		{
			name:     "Different tag types in standalone positions",
			template: "{{#section}}\n{{>partial}}\n{{/section}}",
			want: Lines{
				0: {Type: StandaloneLine, Segments: sectionBeginSegments},
				1: {Type: StandaloneLine, Segments: partialTagSegments},
				2: {Type: StandaloneLine, Segments: sectionEndSegments},
			},
			comment: "Different tag types can all be standalone",
		},
		{
			name:     "Different tag types in standalone positions with trailing newline",
			template: "{{#section}}\n{{>partial}}\n{{/section}}\n",
			want: Lines{
				0: {Type: StandaloneLine, Segments: sectionBeginSegments},
				1: {Type: StandaloneLine, Segments: partialTagSegments},
				2: {Type: StandaloneLine, Segments: sectionEndSegments},
				3: {Type: EmptyLine},
			},
			comment: "Different tag types can all be standalone; trailing newline creates an empty line",
		},
		{
			name:     "Tag inside HTML",
			template: "<div>\n  {{tag}}\n</div>",
			want: Lines{
				0: {Type: TextLine, Segments: textContentSegments},
				1: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, varTagSegment}},
				2: {Type: TextLine, Segments: textContentSegments},
			},
			comment: "Tag on its own line inside HTML is standalone",
		},
		{
			name:     "Tag inside HTML with trailing newline",
			template: "<div>\n  {{tag}}\n</div>\n",
			want: Lines{
				0: {Type: TextLine, Segments: textContentSegments},
				1: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, varTagSegment}},
				2: {Type: TextLine, Segments: textContentSegments},
				3: {Type: EmptyLine},
			},
			comment: "Tag on its own line inside HTML is standalone; trailing newline creates an empty line",
		},
		{
			name:     "Line ends with standalone tag but no newline",
			template: "Text\n{{tag}}",
			want: Lines{
				0: {Type: TextLine, Segments: textContentSegments},
				1: {Type: StandaloneLine, Segments: varTagSegments},
			},
			comment: "Last line containing only a tag is standalone even without trailing newline",
		},
		{
			name:     "Tag preceded by newline and followed by newline",
			template: "\n{{tag}}\n",
			want: Lines{
				0: {Type: EmptyLine},
				1: {Type: StandaloneLine, Segments: varTagSegments},
				2: {Type: EmptyLine}},
			comment: "Empty lines before and after a standalone tag",
		},
		{
			name:     "Tag with leading and trailing newlines",
			template: "\n\n    {{tag}}    \n\n",
			want: Lines{
				0: {Type: EmptyLine},
				1: {Type: EmptyLine},
				2: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, varTagSegment, whitespaceSegment}},
				3: {Type: EmptyLine},
				4: {Type: EmptyLine},
			},
			comment: "Tag with whitespace before and after, surrounded by empty lines",
		},
		{
			name:     "Real-world parent/block pattern",
			template: "{{<parent}}\n{{$block}}Content{{/block}}\n{{/parent}}",
			want: Lines{
				0: {Type: StandaloneLine, Segments: parentBeginSegments},
				1: {Type: InlineLine, Segments: Segments{blockBeginSegment, textContentSegment, blockEndSegment}},
				2: {Type: StandaloneLine, Segments: parentEndSegments},
			},
			comment: "Parent tag and closing tag are standalone, block content line is inline",
		},
		{
			name:     "Real-world parent/block pattern with trailing newline",
			template: "{{<parent}}\n{{$block}}Content{{/block}}\n{{/parent}}\n",
			want: Lines{
				0: {Type: StandaloneLine, Segments: parentBeginSegments},
				1: {Type: InlineLine, Segments: Segments{blockBeginSegment, textContentSegment, blockEndSegment}},
				2: {Type: StandaloneLine, Segments: parentEndSegments},
				3: {Type: EmptyLine}},
			comment: "Parent tag and closing tag are standalone, block content line is inline; trailing newline creates an empty line",
		},
		{
			name:     "Real-world indented template",
			template: "<html>\n  <body>\n    {{>header}}\n    <main>\n      {{#items}}\n        {{.}}\n      {{/items}}\n    </main>\n  </body>\n</html>",
			want: Lines{
				0: {Type: TextLine, Segments: textContentSegments},
				1: {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				2: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, partialTagSegment}},
				3: {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				4: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, MakeBeginTagSegment(SectionTag)}},
				5: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, MakeTagSegment(DotTag)}},
				6: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, MakeEndTagSegment(SectionTag)}},
				7: {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				8: {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				9: {Type: TextLine, Segments: textContentSegments},
			},
			comment: "Partial and section tags should be detected as standalone",
		},
		{
			name:     "Real-world indented template with trailing newline",
			template: "<html>\n  <body>\n    {{>header}}\n    <main>\n      {{#items}}\n        {{.}}\n      {{/items}}\n    </main>\n  </body>\n</html>\n",
			want: Lines{
				0:  {Type: TextLine, Segments: textContentSegments},
				1:  {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				2:  {Type: StandaloneLine, Segments: Segments{whitespaceSegment, partialTagSegment}},
				3:  {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				4:  {Type: StandaloneLine, Segments: Segments{whitespaceSegment, MakeBeginTagSegment(SectionTag)}},
				5:  {Type: StandaloneLine, Segments: Segments{whitespaceSegment, MakeTagSegment(DotTag)}},
				6:  {Type: StandaloneLine, Segments: Segments{whitespaceSegment, MakeEndTagSegment(SectionTag)}},
				7:  {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				8:  {Type: TextLine, Segments: Segments{whitespaceSegment, textContentSegment}},
				9:  {Type: TextLine, Segments: textContentSegments},
				10: {Type: EmptyLine},
			},
			comment: "Partial and section tags should be detected as standalone; trailing newline creates an empty line",
		},
		{
			name:     "Partial with complex indentation",
			template: "<div>\n    {{>partial}}\n        {{>partial}}\n</div>",
			want: Lines{
				0: {Type: TextLine, Segments: textContentSegments},
				1: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, partialTagSegment}},
				2: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, partialTagSegment}},
				3: {Type: TextLine, Segments: textContentSegments},
			},
			comment: "Partial tags with different indentation levels",
		},
		{
			name:     "Partial with complex indentation with trailing newline",
			template: "<div>\n    {{>partial}}\n        {{>partial}}\n</div>\n",
			want: Lines{
				0: {Type: TextLine, Segments: textContentSegments},
				1: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, partialTagSegment}},
				2: {Type: StandaloneLine, Segments: Segments{whitespaceSegment, partialTagSegment}},
				3: {Type: TextLine, Segments: textContentSegments},
				4: {Type: EmptyLine},
			},
			comment: "Partial tags with different indentation levels; trailing newline creates an empty line",
		},
		{
			name:     "Multiple sequential newlines with trailing newline",
			template: "{{tag}}\n\n\n{{tag}}\n",
			want: Lines{
				0: {Type: StandaloneLine, Segments: varTagSegments},
				1: {Type: EmptyLine},
				2: {Type: EmptyLine},
				3: {Type: StandaloneLine, Segments: varTagSegments},
				4: {Type: EmptyLine},
			},
			comment: "Multiple empty lines between tags; trailing newline creates an empty line",
		},
	})
}
